# Generated by Django 5.2.8 on 2025-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_old_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_great_deal",
            field=models.BooleanField(
                default=False,
                help_text="Mark this product as a great deal with discounted pricing",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount (shown when is_great_deal=True)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Current selling price", max_digits=10
            ),
        ),
    ]
