# Generated by Django 5.2.7 on 2025-11-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="agaseke_user",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
