# Generated by Django 5.2.8 on 2025-11-21 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_add_cart_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master toggle for all notifications')),
                ('purchase_created_enabled', models.BooleanField(default=True, help_text='Notify when purchase is confirmed')),
                ('purchase_status_changed_enabled', models.BooleanField(default=True, help_text='Notify when purchase status changes')),
                ('purchase_completed_enabled', models.BooleanField(default=True, help_text='Notify when purchase is completed')),
                ('product_purchased_enabled', models.BooleanField(default=True, help_text='Notify vendor when product is purchased')),
                ('product_purchase_completed_enabled', models.BooleanField(default=True, help_text='Notify vendor when purchase is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='FCM device token', max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_6cf42c_idx'), models.Index(fields=['device_token'], name='notificatio_device__dad3d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('purchase_created', 'Purchase Created'), ('purchase_pending', 'Purchase Pending'), ('purchase_processing', 'Purchase Processing'), ('purchase_awaiting_pickup', 'Purchase Awaiting Pickup'), ('purchase_awaiting_delivery', 'Purchase Awaiting Delivery'), ('purchase_out_for_delivery', 'Purchase Out for Delivery'), ('purchase_completed', 'Purchase Completed'), ('purchase_cancelled', 'Purchase Cancelled'), ('product_purchased', 'Product Purchased (Vendor)'), ('product_purchase_completed', 'Product Purchase Completed (Vendor)')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('fcm_sent', models.BooleanField(default=False, help_text='Whether FCM notification was sent')),
                ('fcm_success', models.BooleanField(default=False, help_text='Whether FCM notification was delivered successfully')),
                ('fcm_error', models.TextField(blank=True, help_text='FCM error message if failed', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
