# Generated by Django 5.2.7 on 2025-11-04 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("awaiting_pickup", "Awaiting Pickup"),
                            ("awaiting_delivery", "Awaiting Delivery"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup from agaseke"),
                            ("delivery", "Home Delivery"),
                        ],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("momo", "Mobile Money"), ("credit", "Credit Card")],
                        default="momo",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Delivery address for home delivery",
                        null=True,
                    ),
                ),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pickup_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("vendor_payment_sent", models.BooleanField(default=False)),
                ("agaseke_commission_sent", models.BooleanField(default=False)),
                (
                    "vendor_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "agaseke_commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_gallery/")),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auxiliary_images",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
